model:
    arch: xxx
data_kitti:
    dataset: kitty
    train_split: train
    val_split: val
    img_rows: 370
    img_cols: 740
    # scale: 255
    mean: [0.35675976, 0.37380189, 0.3764753]
    std: [0.32064945, 0.32098866, 0.32325324]
    path: /home/hoangqc/DATASETS/CITYSCAPES_KITTI
data_cityscapes:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    # scale: 255
    mean: [72.3923111, 82.90893555, 73.15840149]
    std: [45.3192215, 46.15289307, 44.91483307]
    path: /home/hoangqc/DATASETS/CITYSCAPES
training:
    train_iters: 85000
    batch_size: 16
    val_interval: 512
    print_interval: 128
    optimizer:
        lr: 1.0e-4
    l_rate: 1.0e-4
    l_schedule:
    momentum: 0.99
    weight_decay: 0.0005
    resume: kitty_best_model.pkl
classes:
    void_classes: [0, 1, 2, 3, 4, 5, 6, 9, 10, 14, 15, 16, 18, 29, 30, -1]
    valid_classes: [
        7,
        8,
        11,
        12,
        13,
        17,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        31,
        32,
        33,
    ]
    class_names: [
        "unlabelled",
        "road",
        "sidewalk",
        "building",
        "wall",
        "fence",
        "pole",
        "traffic_light",
        "traffic_sign",
        "vegetation",
        "terrain",
        "sky",
        "person",
        "rider",
        "car",
        "truck",
        "bus",
        "train",
        "motorcycle",
        "bicycle",
    ]

#CITYSCAPES_MEAN = [0.28689554, 0.32513303, 0.28389177]
#CITYSCAPES_STD = [0.18696375, 0.19017339, 0.18720214]
#Kitti_mean = [0.35675976, 0.37380189, 0.3764753]
#Kitty_std = [0.32064945, 0.32098866, 0.32325324]